// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjhwidvofgfijwflepie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qaHdpZHZvZmdmaWp3ZmxlcGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTYxMDcsImV4cCI6MjA1OTA3MjEwN30.wx0bqn-OdUW9CyE3TEVLnvjJEJhBGSF4f8b023Q6ekI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);